### ISSUE TITLE
[QUESTION]Question about wamup micro batch and model chunk in seq1F1B-I

### ISSUE THREAD

**Issue by BLue1888** [thunlp/Seq1F1B#3]
Firstly, why warmup micro batch is Eq.6 in paper when interleave is enabled?  That is not consistant with Figure 2 in paper. According to Eq.6, wamup micro batch num of last pp rank is 5, but is 9 in Figure 2.
Secondly, When seq1F1B - I is enabled, do we really not need to adjust the calculation of the model chunk according to the currently calculated chunk sequence?

**Comment by MayDomine** [comment]
This is a mistake in Seq1F1B-I timeline figure. I have already fixed this in latest arxiv submission.
